package com.easybudget.easiestbudget.models

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room Entity representing a User in the application.
 */
@Entity(tableName = "users")
data class User(
    /** Unique ID for the user, auto-generated by Room. */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    /** The display name of the user. */
    val username: String
)